import type { CommandContext, Context } from "grammy";
import { bold } from "../format.js";

export async function helpCmd(ctx: CommandContext<Context>): Promise<void> {
  await ctx.reply(
    [
      `${bold("Phoenix Trading Bot")}`,
      ``,
      `/stats — bot stats (users, trades)`,
      ``,
      `${bold("Setup")}`,
      `/start — create your trading wallet`,
      `/register — register your trader account with Phoenix (auto-verified)`,
      `/tos — review and accept terms`,
      `/setwithdraw [pubkey] — set your withdrawal address`,
      `/unlink confirm — remove wallet from bot`,
      ``,
      `${bold("Wallet")}`,
      `/status — show wallet, balances, settings`,
      `/balance — collateral and free margin`,
      `/deposit — show your deposit address`,
      `/deposit [amount] — credit USDC as Phoenix collateral`,
      `/withdraw [amount] — withdraw USDC to your address`,
      `/exportkey — export your wallet private key (custodial escape hatch)`,
      ``,
      `${bold("Market data")}`,
      `/price [symbol] — mark price + funding`,
      `/markets — list available perps`,
      ``,
      `${bold("Account")}`,
      `/pos — open positions`,
      `/orders — open orders`,
      `/pnl [7d|30d] — realized PnL`,
      `/funding — current funding rates`,
      `/history [7d|30d] — recent trades with realized PnL`,
      ``,
      `${bold("Trade")}`,
      `/long [symbol] [usdc] [lev] [tp=X] [sl=Y] — market long`,
      `/short [symbol] [usdc] [lev] [tp=X] [sl=Y] — market short`,
      `/limit [symbol] [long|short] [usdc] [price] [lev] — limit order`,
      `/close [symbol] [pct] — close position`,
      `/cancel [order_id] — cancel order`,
      `/cancelall [symbol] — cancel all orders for a symbol`,
      ``,
      `${bold("Conditional (TP/SL)")}`,
      `/tp [symbol] [price] — set take-profit on existing position`,
      `/sl [symbol] [price] — set stop-loss on existing position`,
      `/tpsl [symbol] [tp_price] [sl_price] — set both at once`,
      ``,
      `${bold("Alerts")}`,
      `/alert [symbol] [op] [price] — eg /alert SOL > 150`,
      `/alerts — list active alerts`,
      `/delalert [id] — delete an alert`,
      ``,
      `${bold("Settings")}`,
      `/confirm on|off — toggle trade confirmations`,
      `/maxnotional [usdc] — cap per-trade size`,
    ].join("\n"),
    { parse_mode: "HTML" }
  );
}
